/**
 * Created by Milos on 13.2.2015..
 */

var switches = {
    "DJE_SI_GRGA_DRUZE_STARI": "ZA_NAPLATU_TI_NE_MARI\n",
    "IMA_JEDNA_KRCMA_STARA_TAMO_NASRED_BULEVARA": "BULEVARA_REVOLUCIJE\n",
    "VOZI_ME_ZA_SURCIN_PREKO_LEDINA": "TAMO_ZIVI_MOJA_JEDINA\n",
    "VREME_BRZO_PROLAZI": "GODINE_ME_STIZU\n",
    "DUNI_VJETRE_MALO_PREKO_JETRE": "UMRIJECU_OD_BOLA_IZGORJELO_SVE_OD_ALKOHOLA\n",
    "RAKIJA_MI_SE_PRIBLIZILA_DUSI": "CRNA_MI_SE_DZIGERICA_SUSI\n",
    "default": "KUPI_STRIKA_CIPELE_I_DADE_DZEPARAC\n"
};

module.exports = switches;